name 'Analytical Labs-openvpn'
version '1.1'

author 'Tom Barber'
license 'UNKNOWN'
project_page 'UNKNOWN'
source 'https://github.com/luxflux/puppet-openvpn'
summary 'UNKNOWN'
description 'UNKNOWN'
dependency 'ripienaar/concat'
